[package]
name = "ast_combiner"
version = "0.1.0"
authors = ["Daiji Yamashita <yamashita-daiji@sei.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"

